# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MachineIntell',
                'doc_host': 'https://vanhp.github.io',
                'git_url': 'https://github.com/vanhp/MachineIntell',
                'lib_path': 'MachineIntell'},
  'syms': {'MachineIntell.core': {'MachineIntell.core.foo': ('core.html#foo', 'MachineIntell/core.py')}}}