project:
  type: website

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    collapse-below: lg
    logo: /images/gradientv1scale2.jpg
    left:
      - text: "Home"
        href: index.qmd
       
      # - text: "News"
      #   href: news.qmd
      # - text: "Tips & tricks"
      #   href: tips.qmd
      # - text: "Tutorials"  
      #   href: tutoring.qmd
      
      - sidebar:news
      - sidebar:tip
      - sidebar:tutorial

    right:
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/fastai/nbdev/issues
          - text: "Fast.ai Forum"
            icon: chat-right-text
            href: https://forums.fast.ai/
          - text: "FAQ"
            icon: question-circle
            href: getting_started.ipynb#faq

      - text: Blog
        menu:
          - text: "Posts"
            href: blog/index.qmd
        
      - href: about.qmd
        text: About
      - icon: github
        href: "https://github.com/fastai/nbdev"
      - icon: twitter
        href: https://twitter.com/fastdotai
        aria-label: Fast.ai Twitter

  sidebar:
    - id: news

      style: "docked"      
      type: "dark"
      background: "#742787"
      foreground: "#b7e087"

      title: "News"
      contents:
        - news.qmd
        - news1.qmd
        - news2.qmd

    - id: tip
      title: "Tip & Trick"
      contents:
        - tips.qmd
        # navigation items

    - id: tutorial
      title: "Tutorials"
      contents:
        - tutoring.qmd
        - tutoring1.qmd
        - tutoring2.qmd
      # navigation items



  # sidebar:
  #   style: docked
  #   search: true
  #   type: "dark"
  #   background: "#742787"
  #   foreground: "#b7e087"
  #   pinned: false
  #   # contents: 
  #   #   - news
  #   #   - tip & trick
  #   #   - tutoring
  #   #   - help
   

metadata-files: [nbdev.yml, sidebar.yml]