project:
  type: website

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
       
      - text: "News"
        href: news.qmd
      - text: "Tips & tricks"
        href: tips.qmd
      - text: "Tutoring"  
        href: tutoring.qmd
      - text: "Help"
        menu:
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/fastai/nbdev/issues
          - text: "Fast.ai Forum"
            icon: chat-right-text
            href: https://forums.fast.ai/
          - text: "FAQ"
            icon: question-circle
            href: getting_started.ipynb#faq


    right:
      - text: Blog
        menu:
          - text: "Posts"
            href: blog/index.qmd
        
      - href: about.qmd
        text: About
      - icon: github
        href: "https://github.com/fastai/nbdev"
      - icon: twitter
        href: https://twitter.com/fastdotai
        aria-label: Fast.ai Twitter



  sidebar:
    style: floating
    # contents:
    #   - auto: "/*.ipynb"
    #   - section: Tutorials
    #     contents: tutorials
    #   - section: Explanations
    #     contents: explanations
    

metadata-files: [nbdev.yml, sidebar.yml]