project:
  type: website

format:
  html:
    theme: 
      - quartz
      - custom.scss
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    collapse-below: lg
    logo: /images/gradientv1scale2.jpg
    left:
      - text: "Home"
        href: index.qmd
       
      - sidebar:news
      - sidebar:tip
      - sidebar:tutorial

      - text: "Help"   
        menu:   
          - text: "Helping hand"     
            href: ./help/helps.qmd
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/fastai/nbdev/issues
          - text: "Fast.ai Forum"
            icon: chat-right-text
            href: https://forums.fast.ai/
          - text: "FAQ"
            icon: question-circle
            href: getting_started.ipynb#faq


    right:                  
      - text: "Resources"
        menu:   
          - text: "More info"     
            href: ./resources/resource.qmd
          - text: "Report an Issue"
            icon: bug
            href: https://github.com/fastai/nbdev/issues
          - text: "Fast.ai Forum"
            icon: chat-right-text
            href: https://forums.fast.ai/
          - text: "FAQ"
            icon: question-circle
            href: getting_started.ipynb#faq
          
      - text: Blog
        menu:
          - text: "Posts"
            href: blog/index.qmd
        
      - href: about.qmd
        text: About
      - icon: github
        href: "https://github.com/fastai/nbdev"
      - icon: twitter
        href: https://twitter.com/fastdotai
        aria-label: Fast.ai Twitter

  sidebar:
    - id: news

      style: "docked"      
      type: "dark"
      background: "#742787"
      foreground: "#b7e087"

      title: "News"
      contents:
        - ./news/newsall.qmd
        - ./news/news1.qmd
        - ./news/news2.qmd

    - id: tip
      title: "Tip & Trick"
      contents:
        - ./tip/tips.qmd
        # navigation items

    - id: tutorial
      title: "Tutorials"
      contents:
        - ./tutorial/tutoring.qmd
        - ./tutorial/visions/vision.qmd
        - ./tutorial/nlps/nlp.qmd
        - text: "NLP"
          contents:
            - ./tutorial/nlps/rnn.qmd
            
        - text: "Math"
          contents:
            - ./tutorial/math/linearalgebra/lna1.qmd
            - ./tutorial/math/nnMath/nnmath.qmd
            - ./tutorial/math/nnMath/loss/loss.qmd
            - ./tutorial/math/diffEq/diffeq1.qmd
            - ./tutorial/math/diffEq/compoundint.qmd
            # navigation items


   

metadata-files: [nbdev.yml, sidebar.yml]